[package]
name = "storm-lua-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Lua binding/effect analysis, logical project validation and diagnostics"

[lints]
workspace = true

[dependencies]
storm-lua-syntax = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
